def main():
	weeks_str = input("Please enter the number of weeks this semester:  ")
	print(weeks_str, type(weeks_str))
	classes_str = input("Enter the number of classes you are taking:  ")
	print(classes_str, type(weeks_str))
	tuition_str = input("Please enter your tuition:  ")
	print(tuition_str, type(tuition_str))
	weeks = int(weeks_str)
	print(weeks, type(weeks))
	classes = int(classes_str)
	print(classes, type(classes))
	tuition = int(tuition_str)
	print(tuition, type(tuition))
	cost_per_week = ((tuition / classes) / weeks)
	print("Cost per week:", cost_per_week, type(cost_per_week))
	classes_per_week = int(input("please enter the number how many classes a week:  "))
	print(classes_per_week, type(classes_per_week))
	cost_per_class = (cost_per_week/classes_per_week)
	print("Every class cost",cost_per_class, type(cost_per_class))

main()
